spring: 
  profiles: 
    active: dev1
    
---
server:
  port: 7001
spring:
  profiles: dev1
  application:
    name: springcloud-config-eureka
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心去注册自己，因为本机是服务器，服务器是不需要注册的。
    fetch-registry: false #fetch-registry如果为false，则表示自己是注册中心
    service-url: #监控页面
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      
---
server:
  port: 7002
spring:
  profiles: dev2
  application:
    name: springcloud-config-eureka
eureka:
  instance:
    hostname: eureka7002.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心去注册自己，因为本机是服务器，服务器是不需要注册的。
    fetch-registry: false #fetch-registry如果为false，则表示自己是注册中心
    service-url: #监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
      
---
server:
  port: 7003
spring:
  profiles: dev3
  application:
    name: springcloud-config-eureka
eureka:
  instance:
    hostname: eureka7003.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心去注册自己，因为本机是服务器，服务器是不需要注册的。
    fetch-registry: false #fetch-registry如果为false，则表示自己是注册中心
    service-url: #监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      